from separation import INTERACTOME_DEFAULT_PATH


NEW_INTERACTOME_PATH = '../data/human_interactome 20170727.tsv'
#INTERACTOME_PATH = NEW_INTERACTOME_PATH
INTERACTOME_PATH = INTERACTOME_DEFAULT_PATH

SHELVE_PATH = 'results.shelve'
DISEASES_DIR = '../data/diseases/'
